# Generated by Django 3.1.7 on 2021-03-26 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='ContactU',
        ),
    ]
