# Generated by Django 3.1.7 on 2021-03-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20210319_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Quntity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
