# Generated by Django 3.1.7 on 2021-03-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_auto_20210324_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Image',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
