# Generated by Django 3.1.7 on 2021-03-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_auto_20210324_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='GrandTotal',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
    ]
